[package]
name = "plonk_verifier"
version = "0.1.0"
cairo-version = "2.7.0-rc.3"

[config.global]
edition = "2024_07"

[dev-dependencies]
cairo_test = "2.7.0-rc.3"

[dependencies] 
starknet = ">=2.7.0-rc.3" 

[[target.starknet-contract]]
sierra = true
casm = true


